name: anytime
description: Anytime Podcast Player

version: 1.3.5+103

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: 3.16.0

dependencies:
  accessibility_tools: ^1.0.0
  auto_size_text: ^3.0.0
  audio_service: ^0.18.12
  audio_session: ^0.1.18
  connectivity_plus: ^4.0.2
  cupertino_icons: ^1.0.6
  device_info_plus: ^9.0.3
  expand_widget: ^3.1.0
  extended_image: ^8.2.0
  file_picker: ^6.1.1
  flutter_dialogs: ^3.0.0
  flutter_downloader: 1.10.1+2
  flutter_html: ^3.0.0-beta.2
  flutter_html_svg: ^3.0.0-beta.2
  flutter_html_table: ^3.0.0-beta.2
  flutter_launcher_icons: ^0.13.1
  flutter_spinkit: ^5.0.0
  html: ^0.15.0
  intl: ^0.18.0
  intl_translation: ^0.18.2
  just_audio: ^0.9.36
  logging: ^1.0.2
  meta: ^1.9.1
  mp3_info: ^0.2.0
  path: ^1.8.2
  path_provider: ^2.0.11
  path_provider_platform_interface: ^2.0.4
  percent_indicator: 4.2.3
  permission_handler: ^10.4.2
  podcast_search: ^0.6.3
  provider: ^6.0.3
  rxdart: ^0.27.4
  scrollable_positioned_list: ^0.3.7
  sembast: ^3.5.0+1
  share_plus: ^7.2.1
  shared_preferences: ^2.2.2
  sliver_tools: ^0.2.12
  uni_links: ^0.5.1
  url_launcher: ^6.1.12
  xml: 6.3.0

  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  collection: ^1.17.2

dev_dependencies:
  mockito: ^5.2.0
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

dependency_overrides:
  # Override layout grid to fix dependency issue with flutter_html_table
  flutter_layout_grid: ^2.0.5

flutter_icons:
  image_path_android: "assets/images/anytime-logo.png"
  image_path_ios: "assets/images/anytime-logo-ios.png"
  remove_alpha_ios: true
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/anytime-logo.png
    - assets/images/anytime-logo-s.png
    - assets/images/anytime-placeholder-logo.png

    # Certificate authorities
    - assets/ca/lets-encrypt-r3.pem

  fonts:
    - family: SpaceMonoRegular
      fonts:
        - asset: assets/fonts/SpaceMono-Regular.ttf
    - family: SpaceMonoBold
      fonts:
        - asset: assets/fonts/SpaceMono-Bold.ttf
    - family: RobotoCondensedBold
      fonts:
        - asset: assets/fonts/RobotoCondensed-Bold.ttf
    - family: RobotoRegular
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
    - family: MontserratMedium
      fonts:
        - asset: assets/fonts/Montserrat-Medium.otf
    - family: MontserratRegular
      fonts:
        - asset: assets/fonts/Montserrat-Regular.otf
    - family: MontserratBold
      fonts:
        - asset: assets/fonts/Montserrat-Bold.otf
