name: anytime
description: Anytime Podcast Player

version: 1.0.0+51

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  auto_size_text: ^2.1.0
  audio_service: ^0.17.0
  audio_session: ^0.1.0
  connectivity: ^3.0.3
  cupertino_icons: ^1.0.2
  extended_image: ^4.0.1
  file_picker: ^3.0.2+2
  flutter_dialogs: ^2.1.0
  flutter_downloader: 1.5.2
  flutter_html: ^1.3.0
  flutter_launcher_icons: ^0.9.0
  flutter_spinkit: ^5.0.0
  html: ^0.14.0+4
  just_audio: ^0.7.4
  logging: ^1.0.1
  mp3_info: ^0.2.0
  path_provider: ^2.0.1
  percent_indicator: ^3.0.1
  permission_handler: ^6.1.1
  podcast_search: ^0.4.0
  provider: ^5.0.0
  rxdart: ^0.26.0
  scrollable_positioned_list: ^0.1.10
  sembast: ^3.1.0+2
  share_plus: ^2.1.4
  shared_preferences: ^2.0.4
  url_launcher: ^6.0.3
  xml: ^5.1.2

  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  mockito: ^5.0.9
  pedantic: ^1.9.2
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path: "assets/images/anytime-logo.png"
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/anytime-logo.png
    - assets/images/anytime-logo-s.png
    - assets/images/anytime-placeholder-logo.png

  fonts:
    - family: SpaceMonoRegular
      fonts:
        - asset: assets/fonts/SpaceMono-Regular.ttf
    - family: SpaceMonoBold
      fonts:
        - asset: assets/fonts/SpaceMono-Bold.ttf
    - family: RobotoCondensedBold
      fonts:
        - asset: assets/fonts/RobotoCondensed-Bold.ttf
    - family: RobotoRegular
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
    - family: MontserratMedium
      fonts:
        - asset: assets/fonts/Montserrat-Medium.otf
    - family: MontserratRegular
      fonts:
        - asset: assets/fonts/Montserrat-Regular.otf
    - family: MontserratBold
      fonts:
        - asset: assets/fonts/Montserrat-Bold.otf
    - family: JostRegular
      fonts:
        - asset: assets/fonts/jost/Jost-Regular.ttf
