name: anytime
description: Anytime Podcast Player

version: 1.1.0+61

environment:
  sdk: ">=2.10.0 <3.0.0"
  flutter: 2.2.3

dependencies:
  auto_size_text: ^2.1.0
  audio_service: ^0.17.1
  audio_session: ^0.1.6
  connectivity: ^3.0.6
  cupertino_icons: ^1.0.2
  extended_image: ^4.1.0
  file_picker: ^3.0.3
  flutter_dialogs: ^2.1.0
  flutter_downloader: 1.6.1
  flutter_html: ^2.1.2
  flutter_launcher_icons: ^0.9.0
  flutter_spinkit: ^5.0.0
  html: ^0.15.0
  just_audio: ^0.8.0
  logging: ^1.0.1
  mp3_info: ^0.2.0
  path_provider: ^2.0.2
  percent_indicator: ^3.0.1
  permission_handler: ^8.1.4+2
  podcast_search: ^0.5.0
  provider: ^5.0.0
  rxdart: ^0.27.1
  scrollable_positioned_list: ^0.1.10
  sembast: ^3.1.0+2
  share_plus: ^2.1.4
  shared_preferences: ^2.0.6
  url_launcher: ^6.0.7
  xml: ^5.1.2

  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  mockito: ^5.0.9
  pedantic: ^1.9.2
  lints: ^1.0.1
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path_android: "assets/images/anytime-logo.png"
  image_path_ios: "assets/images/anytime-logo-ios.png"
  remove_alpha_ios: true
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/anytime-logo.png
    - assets/images/anytime-logo-s.png
    - assets/images/anytime-placeholder-logo.png

  fonts:
    - family: SpaceMonoRegular
      fonts:
        - asset: assets/fonts/SpaceMono-Regular.ttf
    - family: SpaceMonoBold
      fonts:
        - asset: assets/fonts/SpaceMono-Bold.ttf
    - family: RobotoCondensedBold
      fonts:
        - asset: assets/fonts/RobotoCondensed-Bold.ttf
    - family: RobotoRegular
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
    - family: MontserratMedium
      fonts:
        - asset: assets/fonts/Montserrat-Medium.otf
    - family: MontserratRegular
      fonts:
        - asset: assets/fonts/Montserrat-Regular.otf
    - family: MontserratBold
      fonts:
        - asset: assets/fonts/Montserrat-Bold.otf
    - family: JostRegular
      fonts:
        - asset: assets/fonts/jost/Jost-Regular.ttf
